// Product data and image paths matching public/images (powder.png.jpeg, lequid.png.jpeg, base.png.jpeg)
export const products = [
  {
    id: 'powder',
    name: 'SINAD Powder',
    nameAr: 'مسحوق سِناد',
    price: 4,
    image: '/images/powder.png.jpeg',
    description: 'Eco-friendly heat-resistant tiles from natural materials',
    descriptionAr: 'قرميد بيئي مقاوم للحرارة من مواد طبيعية',
    ingredientsAr: ['أصداف المحار البحري', 'نواة التمر العُمانية', 'مواد رابطة طبيعية'],
    ingredients: ['Oyster shells', 'Omani date seeds', 'Natural binding agents'],
    descriptionFullAr: 'قرميد بيئي مقاوم للحرارة من مواد طبيعية. مناسب للبيئات الساحلية والحارة.',
    descriptionFull: 'Eco-friendly heat-resistant tiles from natural materials. Suitable for coastal and hot environments.',
    howToUseAr: 'اخلط المسحوق مع الماء بنسبة 3:1، ضعه على السطح، اتركه ليجف لمدة 24 ساعة.',
    howToUse: 'Mix powder with water 3:1 ratio, apply to surface, let dry for 24 hours.',
  },
  {
    id: 'paste',
    name: 'SINAD Paste',
    nameAr: 'معجون سِناد',
    price: 4,
    image: '/images/base.png.jpeg',
    description: 'Rust-resistant protective coating for buildings',
    descriptionAr: 'طلاء واقي من الصدأ للمباني',
    ingredientsAr: ['أصداف مطحونة', 'نواة التمر المعالج', 'راتنجات طبيعية'],
    ingredients: ['Ground shells', 'Processed date seeds', 'Natural resins'],
    descriptionFullAr: 'طلاء واقي من الصدأ للمباني. يحمي من الرطوبة والأملاح.',
    descriptionFull: 'Rust-resistant protective coating for buildings. Protects from humidity and salt.',
    howToUseAr: 'ضع طبقة رقيقة على السطح النظيف، اترك ليجف لمدة 12 ساعة.',
    howToUse: 'Apply thin layer on clean surface, let dry for 12 hours.',
  },
  {
    id: 'liquid',
    name: 'SINAD Liquid',
    nameAr: 'سائل سِناد',
    price: 4,
    image: '/images/lequid.png.jpeg',
    description: 'Concrete protection spray with waterproofing',
    descriptionAr: 'رذاذ حماية الخرسانة مع عزل مائي',
    ingredientsAr: ['مستخلص الأصداف', 'زيوت نواة التمر', 'مثبتات طبيعية'],
    ingredients: ['Shell extract', 'Date seed oils', 'Natural stabilizers'],
    descriptionFullAr: 'رذاذ حماية الخرسانة مع عزل مائي. سهل الاستخدام والتطبيق.',
    descriptionFull: 'Concrete protection spray with waterproofing. Easy to use and apply.',
    howToUseAr: 'رش على السطح من مسافة 20 سم، يجف خلال 6 ساعات.',
    howToUse: 'Spray on surface from 20cm distance, dries in 6 hours.',
  },
] as const;

export type ProductId = (typeof products)[number]['id'];